        <div class="col-lg-3 col-md-3 col-sm-12">
            <!-- User Menu -->
            <div class="col-lg-12 col-md-12 col-sm-6">
                <a href="<?php echo (BASE_URL).'customer'; ?>">
                    <img src="http://shop2.loc/media/images/avatar/avatar.png" class="img-circle img-responsive customer-thumbnail" width="150">
                </a>
                <div class="no-padding">
                    <span class="title">
                       فهرست کاربری
                    </span>
                </div>

                <div class="panel-group panel-categories" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading have-sub">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="collapsed" aria-expanded="false">پشتیبانی سامانه</a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse" aria-expanded="true">
                            <div class="list-group">
                                <a href="#" class="list-group-item">لیست پیام ها</a>
                                <a href="#" class="list-group-item">ارسال پیام جدید</a>
                            </div>
                        </div>
                        <div class="panel-heading ">
                            <h4 class="panel-title">
                                <a href="detail.php">اطلاعات کاربری</a>
                            </h4>
                        </div>
                        <div class="panel-heading ">
                            <h4 class="panel-title">
                                <a href="#">ارسال آواتار</a>
                            </h4>
                        </div>
                        <div class="panel-heading ">
                            <h4 class="panel-title">
                                <a href="<?php echo (BASE_URL.'customer/logout.php'); ?>">خروج</a>
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End User Menu -->
        </div>