<?php
$cartCount = count($cartItems);
?>

<table class="table table-bordered tbl-cart table-hover">
                    <thead>
                        <tr class="text-center">
                            <td class="tbl-cart-image hidden-xs">تصویر</td>
                            <td>نام محصول</td>
                            
                            
                            <td class="td-qty">تعداد</td>
                            <td>فی</td>
                            <td class="price-total">جمع</td>
                            <td class="tbl-cart-remove">حذف</td>
                        </tr>
                    </thead>
                        <tbody>
                        <?php
                                $totalPrice=0;
                                if($cartCount>0):
                                foreach ($cartItems as $item):
                                        $totalPrice+=($item['count'] * $item['product_price']);
                        ?>
                            
                            <tr>
                                <td class="hidden-xs">
                                    <a href="<?php echo productUrl($item['id']); ?>">
                                        <img src="media/product/product-1.jpg" alt="Age Of Wisdom Tan Graphic Tee" title="" class="tbl-cart-image" width="47" height="47">
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo productUrl($item['id']); ?>"><?php echo ($item['product_name']); ?></a>
                                </td>
                                
                                <td>
                                    <div class="input-group bootstrap-touchspin">
                                        <span class="input-group-btn"></span>
                                        <span class="input-group-addon bootstrap-touchspin-prefix" style="display: none;"></span>
                                            <input type="text" name="" value="<?php echo ($item['count']); ?>" class="input-qty form-control text-center" style="display: block;">
                                        <span class="input-group-addon bootstrap-touchspin-postfix" style="display: none;"></span>
                                    </div>
                                </td>
                                <td class="price-single"><?php echo ($item['product_price']); ?>
                                    ريال
                                </td>
                                <td>
                                    <?php echo ($item['count'] * $item['product_price']); ?>
                                    ريال
                                </td>
                                <td class="text-center cart-remove-box">
                                    <a href="#" rel="2">
                                        <i class="glyphicon glyphicon-trash cart-item-remove" onclick="(function(){location='<?php echo (removeFromCart($item)); ?>';})()"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                           <?php endif; ?> 
                            <tr>
                                <td colspan="3" align="left">جمع کل</td>
                                <td class="price-total text-center" colspan="3"><strong> <?php echo ($totalPrice); ?>
                                        ريال</strong>
                                </td>
                            </tr>
                        </tbody>
                    </table>