<div class="slider">
    <div class="bx-wrapper" style="max-width: 100%; margin: 0 auto;">
        <div class="bx-viewport" style="max-width: 100%; overflow: hidden; position: relative; max-height: 300px;">
            <ul class="bxslider">
                <?php
                    foreach ($sliderNumberOne as $slide):
                        
                ?>
                <li>
                    <a href="<?php echo(productUrl($slide['id'])); ?>"><img src="<?php echo (productImageUrl($slide)); ?> " style="max-height: 295px;"></a>
                </li>
                <?php

                    endforeach;
                ?>
            </ul>
        </div> <!-- bx-viewport -->
        <div class="bx-controls bx-has-controls-direction">
            <!-- <div class="bx-controls-direction">
                <a class="bx-prev">prev</a>
                <a class="bx-next">next</a>
            </div> -->
        </div>
    </div> <!-- bx-wrapper -->
</div>


