
    <!-- Body -->
    <div class="row">
        <!-- Sidebar -->
        <div class="col-lg-3 col-md-3 col-sm-12">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                

<!-- Login Form -->
                <div class="no-padding">
                    <span class="title">
                        ورود به فروشگاه
                    </span>
                </div>
                <form role="form" method="post" action="" >
                    <div class="form-group">
                        <div class="input-group login-input">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            
                            <input type="text" name="email" class="form-control" placeholder="آدرس ایمیل">
                            
                        </div>
                        <br>
                        <div class="input-group login-input">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            
                            <input type="password" name="password" class="form-control" placeholder="رمز عبور">
                            
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> مرا بخاطر بسپار
                            </label>
                        </div>
                        <button type="submit" name="login" class="btn btn-sm btn-primary pull-left">ورود  </button>
                        
                        <a href="#" class="btn btn-warning btn-sm">بازیابی رمز عبور</a>
                    </div>
                </form>
<!-- Login Form-->

            </div>
            
        </div>
    <div class="clearfix visible-sm"></div>
        <!-- End Sidebar -->
        
        <!--main box-->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">
                    عضویت
                </span>
            </div>
            <div class="col-lg-12 col-sm-12 hero-feature">
<!-- Register -->

            <div class="white-container">
                    <p>
    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
                    </p>

                <!-- Form Register -->
                <form method="post" action="">
                    
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="first_name">نام (*)</label>
                        <input type="text" class="form-control" name="firstName" placeholder="نام" id="first_name"><br clear="all">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="last_name">نام خانوادگی (*)</label>
                        <input type="text" class="form-control" name="lastName" placeholder="نام خانوادگی" id="last_name"><br clear="all">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="email">Email (*)</label>
                        <input type="text" class="form-control" name="email" placeholder="آدرس پست الکترونیکی" id="email"  ><br clear="all">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="username">شماره تلفن همراه (*)</label> 
                        <input type="text" name="mobile" class="form-control" placeholder="شماره تلفن همراه" id="mobile"><br clear="all">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="confirm_password"> رمز عبور (*)</label>
                        <input type="password" class="form-control" name="password" id="confirm_password"><br clear="all">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                       <label for="male">جنسیت (*)</label><br clear="all">
                       <div class="checkbox">
                            <label for="male" >
                                <input type="radio" id="male"  name="gender" value="1" >  مذکر 
                            </label> 
                            <label for="female" >
                                <input type="radio" id="female" name="gender" value="0" > مونث 
                            </label><br clear="all">  
                       </div>
                    </div>
                    <div class="clearfix"></div>
            <!--                    
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> ضمن مطالعه <a href="#">قوانین </a>  با تمام موارد موافقم.
                        </label>
                    </div>
            -->
                    <button class="btn btn-danger" type="submit" name="signup">ثبت نام</button>
                </form>
                <!-- End Form Register -->
            </div>

<!-- End Register -->
            </div> <!-- col-lg-12 col-sm-12 hero-feature-->
        </div> <!-- end main box -->
    </div>
    <!-- End Body -->

