<!DOCTYPE html>
<html>
<head lang="fa">
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="<?php echo(loadCSS('style.css')); ?>" >
</head>
<body>
<header></header>
<nav></nav>
<div class="container"><?php echo(isset($content)?$content:''); ?></div>
<footer></footer>
<script type="text/javascript" src="<?php echo(loadJS('jquery-1.11.0.min.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('main.js')); ?>" ></script>
</body>
</html>