<!DOCTYPE html>
<html>
	<head lang="fa">
	    <meta charset="UTF-8">

	    <!-- Bootstrap core CSS -->
	    <link href="<?php echo(loadCSS('bootstrap.min.css')); ?>" rel="stylesheet">
	    <link href="<?php echo(loadCSS('bootstrap-rtl.min.css')); ?>" rel="stylesheet">

	    <link href="<?php echo(loadCSS('jquery.bxslider.css')); ?>" rel="stylesheet">
	        
	    <!-- Custom styles for this template -->
	    <link href="<?php echo(loadCSS('custom.css')); ?>" rel="stylesheet">
	    
	    <title>فروشگاه تحلیل داده</title>
	</head>
	<body>


		<header>
		    <div class="container margin-top-20 margin-bottom-10">
		        <div class="row">
		            <!-- Logo -->
		            <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
		                <div class="header-logotype">
                                    <a href="<?php echo (BASE_URL); ?>">
		                        فروشگاه مجازی
		                    </a>
		                    <div class="Slogan">
		                        لورم ایپسوم متن ساختگی با تولید
		                    </div>
		                </div>
		            </div>
		            
		            <!-- search box -->
		            <div class="col-lg-5 col-md-5 col-sm-6 col-xs-7">
		                <form action="">
		                    <div class="input-group">
		                        <input type="text" class="form-control" placeholder="جستجو محصول">
		                        <span class="input-group-btn">
		                            <button class="btn btn-default" type="submit">
		                                <i class="glyphicon glyphicon-search"></i>
		                            </button>
		                        </span>
		                    </div>
		                </form>
		            </div>
		            
		            <!-- Cart -->
		            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-5"><?php echo (loadElement('cart')); ?></div>
		        </div> <!-- Row -->
		    </div> <!-- container -->
		</header>


		<!-- Navigation -->

		<nav class="navbar navbar-inverse" role="navigation">
		    <div class="container">
		        <div class="navbar-header">
		        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-ex1-collapse">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		        </button>
		        <!-- Text Logo on Mobile -->
		        <a href="#" class="navbar-brand visible-xs">
		            فروشگاه مجازی
		        </a>
		        </div>
		        <div class="navbar-collapse navbar-ex1-collapse collapse">
		            <ul class="nav navbar-nav">
		                <li>
		                    <a href="<?php echo (BASE_URL); ?>">صفحه اصلی</a>
		                </li>
		                <li>
		                    <a href="#">محصولات</a>
		                </li>
		                <li>
		                    <a href="#">سبد خرید</a>
		                </li>
		                <li>
		                    <a href="#">تسویه حساب</a>
		                </li>
		                <li>
		                    <a href="#">سایر صفحات</a>
		                </li>
		                
		            </ul>
		        </div>
		        
		    </div>
		</nav> <!-- End Navigation -->


		<!-- container -->
		<div class="container main-container"><?php echo($content); ?></div>
		<!-- End container -->





		<footer>
		    <div class="container margin-bottom-10">
		        <div class="col-lg-4 col-md-4 col-sm-6">
		            <div class="column">
		                <h4>
		                    دسترسی سریع
		                </h4>
		                <ul>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                </ul>
		            </div>
		        </div>
		        <div class="col-lg-4 col-md-4 col-sm-6">
		            <div class="column">
		                <h4>
		                    دسترسی سریع
		                </h4>
		                <ul>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                </ul>
		            </div>
		        </div>
		        <div class="col-lg-4 col-md-4 col-sm-6">
		            <div class="column">
		                <h4>
		                    دسترسی سریع
		                </h4>
		                <ul>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                    <li><a href="#">درباره ما</a></li>
		                </ul>
		            </div>
		        </div>
		    </div>
		    <div class="navbar-inverse text-center copyright">
		        کلیه حقوق محفوظ می باشد.
		    </div>
		</footer>

		<a href="#top" class="back-top text-center" onclick="$('body,html').animate({scrollTop:0},500); return false" style="display: block;"><i class="glyphicon glyphicon-chevron-up"></i></a>
		



		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script type="text/javascript" src="<?php echo(loadJS('jquery-1.11.2.min.js')); ?>" ></script>
		<script type="text/javascript" src="<?php echo(loadJS('bootstrap.min.js')); ?>" ></script>
		<script type="text/javascript" src="<?php echo(loadJS('jquery.bxslider.min.js')); ?>" ></script>
                <script type="text/javascript" src="<?php echo(loadJS('bootstrap.touchspin.js')); ?>" ></script>
                <script type="text/javascript" src="<?php echo(loadJS('jquery.zoom.min.js')); ?>" ></script>
		<script type="text/javascript" src="<?php echo(loadJS('mimity.js')); ?>" ></script>
		<script type="text/javascript" src="<?php echo(loadJS('main.js')); ?>" ></script>


	</body>
</html>