<!DOCTYPE html>
<html>
<head lang="fa">
    <meta charset="UTF-8">
    <title>فروشگاه تحلیل داده</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />

    <!-- Bootstrap core CSS -->
    <link href="<?php echo(loadCSS('bootstrap.min.css')); ?>" rel="stylesheet">
    <link href="<?php echo(loadCSS('bootstrap-rtl.min.css')); ?>" rel="stylesheet">

    <link href="<?php echo(loadCSS('jquery.bxslider.css')); ?>" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo(loadCSS('custom.css')); ?>" rel="stylesheet">
    
<script type="text/javascript" src="<?php echo(loadJS('tinymce/tinymce.min.js')); ?>" ></script>
    
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    language : 'fa_IR',
    theme: "modern",
    height : 300,
    directionality : 'rtl',
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
    
});
</script>

</head>
<body>


<header>
    <div class="container margin-top-20 margin-bottom-10">
        <div class="row">
            <!-- Logo -->
            <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
                <div class="header-logotype">
                    <a href="../index.html">
                        فروشگاه مجازی
                    </a>
                    <div class="Slogan">
                        لورم ایپسوم متن ساختگی با تولید
                    </div>
                </div>
            </div>
            <!-- Admin Notofication -->
            <div class="col-lg-3 col-md-3 hidden-xs pull-left">
                <div class="admin-top-navbar">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <i class="glyphicon glyphicon-bell"></i>
                                    <span class="badge badge-default">
                                    7 </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <i class="glyphicon glyphicon-envelope"></i>
                                    <span class="badge badge-default">
                                    3 </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <i class="glyphicon glyphicon-shopping-cart"></i>
                                    <span class="badge badge-default">
                                    59 </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-off"></i>
                            </a>
                        </li>

                    </ul>
                </div> <!-- End Admin Notofication -->
            </div>
            
        </div> <!-- Row -->
    </div> <!-- container -->
</header>

<!-- Navigation -->

<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!-- Text Logo on Mobile -->
        <a href="#" class="navbar-brand visible-xs">
            فروشگاه مجازی
        </a>
        </div>
        <div class="navbar-collapse navbar-ex1-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="<?php echo (BASE_URL).'admin'; ?>">صفحه اصلی</a>
                </li>
                <li class="nav-dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       مدیریت مطالب
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">لیست مطالب</a></li>
                        <li><a href="#">افزودن مطلب جدید</a></li>
                    </ul>
                </li>
                <li class="nav-dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        مدیریت محصولات
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin/product/list.php">لیست محصولات</a></li>
                        <li><a href="/admin/product/add.php">افزودن محصول جدید</a></li>
                        <li><a href="/admin/product/edit.php">ویرایش محصول</a></li>
                        <li><a href="best-selling.html">پرفروش ترین محصول</a></li>
                        <li><a href="#">پربازدید ترین محصول</a></li>
                    </ul>
                </li>
                <li class="nav-dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        مدیریت مشتریان
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin/customer/list.php">مشاهده لیست مشتریان</a></li>
                        <li><a href="/admin/customer/add.php">افزودن مشتری جدید</a></li>
                        <li><a href="/admin/product/edit.php">ویرایش مشتری </a></li>
                    </ul>
                </li>
                <li>
                    <a href="/admin/setting/index.php">تنظیمات</a>
                </li>
            </ul>
        </div>
        
        
    </div> <!-- container -->
</nav> <!-- End Navigation -->
<div class="container main-container">
    <!-- Body -->

    <div class="row">
        <?php
            // show message
            echo (loadElement('message'));
            echo(isset($content)?$content:'');
        ?>

    </div> <!-- Row -->
    
    <!-- End Body -->
</div> <!-- Container -->
<footer>
    <div class="container margin-bottom-10">
        <div class="col-lg-3 col-md-3 col-sm-6">
            <div class="column">
                <h4>
                    دسترسی سریع
                </h4>
                <ul>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
            <div class="column">
                <h4>
                    دسترسی سریع
                </h4>
                <ul>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
            <div class="column">
                <h4>
                    دسترسی سریع
                </h4>
                <ul>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
            <div class="column">
                <h4>
                    دسترسی سریع
                </h4>
                <ul>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">درباره ما</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="navbar-inverse text-center copyright">
        کلیه حقوق محفوظ می باشد.
    </div>
</footer>
<a href="#top" class="back-top text-center" onclick="$('body,html').animate({scrollTop:0},500); return false" style="display: block;">
    	<i class="glyphicon glyphicon-chevron-up"></i>
</a>








<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="<?php echo(loadJS('jquery-1.11.2.min.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('bootstrap.min.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('jquery.bxslider.min.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('bootstrap.touchspin.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('jquery.zoom.min.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('highcharts.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('bootstrap-filestyle.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('mimity.js')); ?>" ></script>


<script type="text/javascript" src="<?php echo(loadJS('main.js')); ?>" ></script>
<script type="text/javascript" src="<?php echo(loadJS('admin.js')); ?>" ></script>

</body>
</html>