                <!-- Cart Page -->
<!-- Body -->

    <div class="row">
        <!-- Sidebar -->
        <div class="col-lg-3 col-md-3 col-sm-12">
            <!-- Best Product-->
            <div class="col-lg-12 col-md-12 col-sm-12 visible-lg visible-md">
                <div class="no-padding">
                    <span class="title">
                        پرفروش ترین محصولات
                    </span>
                </div>
                
                    <?php echo(loadElement('bestselling')); ?>
                
            </div>
            <!-- End Best Product-->
            
        </div> <!-- End col-lg-3 col-md-3 col-sm-12 -->
    <div class="clearfix visible-sm"></div>
        <!-- End Sidebar -->
        
        <!--cart table-->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">
                    سبد خرید
                </span>
            </div>
            <div class="col-lg-12 col-sm-12 hero-feature">

                
<table class="table table-bordered tbl-cart table-hover">
    <thead>
        <tr class="text-center">
            <td class="tbl-cart-image hidden-xs">تصویر</td>
            <td>نام محصول</td>


            <td class="td-qty">تعداد</td>
            <td>فی</td>
            <td class="price-total">جمع</td>
            <td class="tbl-cart-remove">حذف</td>
        </tr>
    </thead>
    <tbody>
    <?php
    
            $cartCount = count($cartItems);
            $totalPrice=0;
            if($cartCount>0):
            foreach ($cartItems as $cartItem):
                    $totalPrice+=($cartItem['count'] * $cartItem['product_price']);
    ?>
                            
    <tr>
        <td class="hidden-xs">
            <a href="<?php echo productUrl($cartItem['id']); ?>">
                <img src="<?php echo(productImageUrl($cartItem)); ?>" alt="Age Of Wisdom Tan Graphic Tee" title="" class="tbl-cart-image" width="47" height="47">
            </a>
        </td>
        <td>
            <a href="<?php echo productUrl($cartItem['id']); ?>"><?php echo ($cartItem['product_name']); ?></a>
        </td>

        <td>
            <div class="input-group bootstrap-touchspin">
                <span class="input-group-btn"></span>
                <span class="input-group-addon bootstrap-touchspin-prefix" style="display: none;"></span>
                    <input type="text" name="" value="<?php echo ($cartItem['count']); ?>" class="input-qty form-control text-center" style="display: block;">
                <span class="input-group-addon bootstrap-touchspin-postfix" style="display: none;"></span>
            </div>
        </td>
        <td class="price-single"><?php echo ($cartItem['product_price']); ?>
            ريال
        </td>
        <td>
            <?php echo ($cartItem['count'] * $cartItem['product_price']); ?>
            ريال
        </td>
        <td class="text-center cart-remove-box">
            <a href="#" rel="2">
                <i class="glyphicon glyphicon-trash cart-item-remove" onclick="(function(){location='<?php echo (removeFromCart($cartItem)); ?>';})()"></i>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
       <?php endif; ?> 
    
        <tr>
            <td colspan="3" align="left">جمع کل</td>
            <td class="price-total text-center" colspan="3"><strong> <?php echo ($totalPrice); ?>
                    ريال</strong>
            </td>
        </tr>
    </tbody>
</table>
                
                        <div class="btn-group btns-cart pull-left">
                                <button type="button" class="btn btn-primary" onclick="window.location='<?php echo BASE_URL.'/category'; ?>'"><i class="glyphicon glyphicon-circle-arrow-right"></i> بازگشت به فروشگاه</button>
                                <button type="button" class="btn btn-primary">برورزرسانی سبد خرید</button>
                                <button type="button" class="btn btn-primary" onclick="window.location='checkout.php'">تسویه حساب <i class="glyphicon glyphicon-circle-arrow-left"></i></button>
                        </div>
            </div>


        </div> <!--End cart table-->
        
    
    </div>

    

<!-- End Body -->
