<div class="col-lg-3 col-md-3 col-sm-12">
    <!-- Categories Menu -->
    <div class="col-lg-12 col-md-12 col-sm-6">
        <div class="no-padding">
            <span class="title">
               لیست تنظیمات
            </span>
        </div>

        <div class="panel-group panel-categories" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading have-sub">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="collapsed" aria-expanded="false">تنظیمات اولیه </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse" aria-expanded="true">
                    <div class="list-group">
                        <a href="#" class="list-group-item">لیست برند ها</a>
                        <a href="#" class="list-group-item"> لیست کشورها</a>
                    </div>
                </div>

                
                <div class="panel-heading ">
                    <h4 class="panel-title">
                        <a href="#">یک منو کاربردی</a>
                    </h4>
                </div>
                <div class="panel-heading ">
                    <h4 class="panel-title">
                        <a href="#">یک منو کاربردی</a>
                    </h4>
                </div>
            </div>
        </div>
    </div>
    <!-- End Categories Menu -->

</div>
        
        
        <div class="clearfix visible-sm"></div>
        
<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 product-detail-tab">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active" style="padding-right: 2px;"><a href="#generalSetting" data-toggle="tab">تنظیمات عمومی</a></li>
            <li><a href="#lastsells" data-toggle="tab">آخرین فروش ها</a></li>
            <li><a href="#newproducts" data-toggle="tab">جدیدترین محصولات</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="generalSetting">
                <div class="well">
                    <!-- General Setting -->
                    <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td class="tbl-width-150">
                                نام فروشگاه
                            </td>
                            <td>
                                <input class="form-control">
                            </td>
                        </tr>
                        <tr>
                            <td class="tbl-width-150">
                                توضیحات فروشگاه
                            </td>
                            <td>
                                <input class="form-control">
                            </td>
                        </tr>
                        <tr>
                            <td class="tbl-width-150">
                                درصد ارزش افزوده
                            </td>
                            <td>
                                <input class="form-control">
                            </td>
                        </tr>
                    </thead>
                </table>
                    
                    
                    
                    
                    <!-- End General Setting -->
                </div>
        </div>
        <div class="tab-pane" id="lastsells">
            <div class="well"> <!-- Last sells -->

            <table class="table table-bordered tbl-cart table-hover">
                <thead>
                    <tr class="text-center">
                        <td class="tbl-cart-image hidden-xs">ردیف</td>
                        <td>نام محصول</td>
                        <td class="td-count">تعداد</td>
                        <td class="td-qty">تاریخ</td>
                        <td>فی</td>
                        <td class="price-total">جمع</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="hidden-xs text-center">1</td>
                        <td>
                            <a href="../detail.html">
                                 تیشرت خوبـــ   
                            متن طولانی متن طولانی متن طولانی متن طولانی 
                            </a>
                        </td>

                        <td class="text-center">
                            155
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                        <td>
                            20.000.000.000
                            ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">2</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">3</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">4</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">5</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">6</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>

                </tbody>
            </table>


            </div> <!-- End Last sells -->
        </div>
        <div class="tab-pane" id="newproducts">
            <div class="well">

            <table class="table table-bordered tbl-cart table-hover">
                <thead>
                    <tr class="text-center">
                        <td class="tbl-cart-image hidden-xs">ردیف</td>
                        <td>نام محصول</td>
                        <td class="">تعداد بازدید</td>
                        <td class="td-qty">تاریخ</td>
                        <td>فی</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="hidden-xs text-center">1</td>
                        <td>
                            <a href="../detail.html">
                            شلوارک
                            </a>
                        </td>

                        <td class="text-center">
                            155
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">2</td>
                        <td>
                            <a href="../detail.html">
                            پیراهن 
                            </a>
                        </td>

                        <td class="text-center">
                            1
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">3</td>
                        <td>
                            <a href="../detail.html">
                            شلوار بچه گانه
                            </a>
                        </td>

                        <td class="text-center">
                            2
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">4</td>
                        <td>
                            <a href="../detail.html">
                            شلوار مردانه
                            </a>
                        </td>

                        <td class="text-center">
                            55
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">5</td>
                        <td>
                            <a href="../detail.html">
                                لباس خوب
                            </a>
                        </td>

                        <td class="text-center">
                            3
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">6</td>
                        <td>
                            <a href="../detail.html">
                                 تیشرت خوبـــ   
                            متن طولانی متن طولانی متن طولانی متن طولانی 
                            </a>
                        </td>

                        <td class="text-center">
                            4
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                    </tr>


                </tbody>
            </table>
        </div>
        </div>
    </div>
</div> <!-- col-xs-12 product-detail-tab -->