<div class="col-lg-3 col-md-3 col-sm-12">
مشتریان :         <a href="customer/add.php">اضافه کردن</a> / <a href="customer/edit.php">ویرایش</a> /  <a href="customer/list.php">نمایش</a> </br>________________________________</br>
سفارشات:           <a href="order/list.php">نمایش</a></br>________________________________</br>
محصولات:          <a href="product/add.php">اضافه کردن</a> / <a href="product/edit.php">ویرایش</a> / <a href="product/list.php">نمایش</a></br>
</div>


