

        <div class="col-lg-12 col-md-12 col-xs-12">
            <span class="title icon-customer-list">
                    لیست مشتریان

                <button type="button" class="btn btn-primary pull-left collapsed" data-toggle="collapse" data-target="#search" aria-expanded="false">
                    جستجو پیشرفته
                </button>
                    <div class="clearfix"></div>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="col-lg-12 col-md-12">
<div id="search" class="collapse open">

        <div class="col-lg-12 col-md-12 col-sm-12"> <!-- Search Content -->
            <table class="table table-bordered tbl-checkout">
                <tbody>
                    <tr>
                        <td>
                            نام 
                        </td>
                        <td class="tbl-width-250">
                            <input type="text" class="form-control">
                        </td>
                        <td>
                            نام خانوادگی
                        </td>
                        <td  class="tbl-width-250">
                            <input type="text" class="form-control">
                        </td>
                        <td>
                           شماره تلفن همراه
                        </td>
                        <td  class="tbl-width-250">
                            <input type="text" class="form-control">
                        </td>
                    </tr>
                </tbody>
            </table> 
            <input type="submit" name="btnSearch" value="جستجو" class="btn btn-success pull-left">
            <br><br>
            
        </div> <!-- Search Content -->      
    </div>
                
                <table class="table table-bordered table-hover table-responsive tbl-cart">
                    <thead>
                        <tr class="text-center">
                            <td class="tbl-width-50">
                                ردیف
                            </td>
                            <td class="tbl-width-150">
                                نام 
                            </td>
                            <td class="tbl-width-150">
                                نام خانوادگی
                            </td>
                            <td class="tbl-width-100">
                                شماره تلفن همراه
                            </td>
                            <td class="tbl-width-100">
                                آدرس پست الکترونیکی
                            </td>
                            <td class="tbl-width-150">
                                تاریخ عضویت
                            </td>
                            <td class="tbl-width-200">
                                دستورات
                            </td>
                        </tr>
                    </thead>
                    <tbody>
<?php foreach($customers as $customer): ?>
                        <tr>
                            <td class="text-center"><?php echo ($customer['id']); ?></td>
                            <td class="text-center"><a href="<?php echo(sprintf('/admin/customer/edit.php?p=%d',$customer['id']));?>"><?php echo ($customer['first_name']); ?></a></td>
                            <td class="text-center"><?php echo ($customer['last_name']); ?></td>
                            <td class="text-center"><?php echo ($customer['mobile']); ?></td>
                            <td class="text-center"><?php echo ($customer['email']); ?></td>
                            <td class="text-center"><?php echo ($customer['register_date']); ?></td>
                            <td class="text-center">
                                <img src="<?php echo(loadSkinImg('admin/customer_info.png')); ?>" data-toggle="tooltip" data-placement="bottom" title="مشاهده اطلاعات مشتری"/>
                                <img src="<?php echo(loadSkinImg('admin/customer_edit.png')); ?>" data-toggle="tooltip" data-placement="bottom" title="ویرایش مشتری"/>
                                <img src="<?php echo(loadSkinImg('admin/customer_message.png')); ?>" data-toggle="tooltip" data-placement="bottom" title="ارسال پیام"/>
                                <img src="<?php echo(loadSkinImg('admin/sms.png')); ?>" data-toggle="tooltip" data-placement="bottom" title="ارسال پیامک"/>
                                <img src="<?php echo(loadSkinImg('admin/customer_delete.png')); ?>" data-toggle="tooltip" data-placement="bottom" title="حذف مشتری"/>
                            </td>
                        </tr>
<?php endforeach; ?>
                        
                    </tbody>
                </table>
            </div>
        </div>


 <!-- Row --> 
 
 <?php
 
//echo strtotime('2015-05-23 23:13:02');
 //echo (loadElement('persiandate','2015-05-23 23:13:02'));
 //persianDate('2015-05-23 23:13:02');

