
        <!-- Sidebar -->
        
    <?php echo(loadElement('customermenu')); ?>
        
    <div class="clearfix visible-sm"></div>
        <!-- End Sidebar -->
        
        <!--cart table-->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">
                    اطلاعات مشتری
                </span>
            </div>
            <div class="col-lg-12 col-sm-12 hero-feature">
<!-- chekout table -->
                
            <form name="customerDetails" method="POST" action="" >
            <table class="table table-bordered tbl-checkout">
                <tbody>
                    <tr>
                        <td>نام</td>
                        <td>
                            <input type="text" id="product_name" name="txtName" 
                                value="<?php echo htmlentities(isset($customerDetails['customer_name'])?$customerDetails['customer_name']:'1', ENT_QUOTES, 'UTF-8') ?>" class="form-control" />
                        </td>
                        <td>نام خانوادگی</td>
                        <td>
                            <input type="text" name="txtFamily" class="form-control" value="<?php echo $customerDetails['customer_family']; ?>">
                        </td>
                    </tr>
                        <tr>
                            <td>Email</td>
                            <td>
                                <input type="text" name="txtEmail" class="form-control" value="<?php echo $customerDetails['customer_email']; ?>">
                            </td>
                            <td>شماره تلفن همراه</td>
                            <td>
                                <input type="text" name="txtMobile" class="form-control" value="<?php echo $customerDetails['customer_mobile']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td>آدرس</td>
                            <td colspan="3">
                                <textarea name="txtAddress" class="form-control" style="resize: vertical" rows="3" ><?php echo $customerDetails['customer_address']; ?></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>شهر</td>
                            <td>
                                <input type="text" name="txtCity" class="form-control" value="<?php echo $customerDetails['customer_city']; ?>">
                            </td>
                            <td>استان / شهرستان:</td>
                            <td>
                                <input type="text" name="txtState" class="form-control" value="<?php echo $customerDetails['customer_state']; ?>">
                            </td>
                        </tr>
                        <tr>     
                            <td>کدپستی</td>
                            <td>
                                <input type="text" name="txtZipCode" class="form-control" value="<?php echo $customerDetails['customer_zipcode']; ?>">
                            </td>
                            <td>شماره تماس اضطراری</td>
                            <td>
                                <input type="text" name="txtEmergencyNumber" class="form-control" value="<?php echo $customerDetails['customer_emergency_number']; ?>">
                            </td>

                        </tr>
                    </tbody>
                </table>

                <div class="btn-group btns-cart pull-left">
                    <button type="submit" name="btnEditSubmit" class="btn btn-success">ثبت تغییرات</button>
                </div>
            </form>
<!-- Chekout Table -->
            </div> <!-- col-lg-12 col-sm-12 hero-feature -->


        </div> <!--End cart table-->
        
    
    </div>

    

    <!-- End Body -->
