    <?php echo(loadElement('customermenu')); ?>
        
        
        <div class="clearfix visible-sm"></div>
        
<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 product-detail-tab">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active" style="padding-right: 2px;"><a href="#notice" data-toggle="tab">آخرین اعلان ها</a></li>
            <li><a href="#lastbuy" data-toggle="tab">آخرین خرید ها</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="notice">
                <div class="well">
                    <p>
                        لیست پیغام ها ...
                    </p>
                </div>
        </div>
        <div class="tab-pane" id="lastbuy">
            <div class="well"> <!-- last buy -->

            <table class="table table-bordered tbl-cart table-hover">
                <thead>
                    <tr class="text-center">
                        <td class="tbl-cart-image hidden-xs">ردیف</td>
                        <td>نام محصول</td>
                        <td class="td-count">تعداد</td>
                        <td class="td-qty">تاریخ</td>
                        <td>فی</td>
                        <td class="price-total">جمع</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="hidden-xs text-center">1</td>
                        <td>
                            <a href="../detail.html">
                                 تیشرت خوبـــ   
                            متن طولانی متن طولانی متن طولانی متن طولانی 
                            </a>
                        </td>

                        <td class="text-center">
                            155
                        </td>
                        <td class="text-center">
                            94/02/01
                        </td>
                        <td class="price-single">100.000.000
                            ريال
                        </td>
                        <td>
                            20.000.000.000
                            ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">2</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">3</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">4</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">5</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>
                    <tr>
                        <td class="hidden-xs text-center">6</td>
                        <td><a href="../detail.html">پیرهن خیلی ارزان</a>
                        </td>
                        <td class="text-center"> 3 </td>
                        <td class="text-center">
                            94/01/25
                        </td>
                        <td class="price-single">20.000
                        ريال
                        </td>
                        <td>50.000.000
                        ريال
                        </td>
                    </tr>

                </tbody>
            </table>


            </div> <!-- End last buy -->
        </div>
    </div>
</div> <!-- col-xs-12 product-detail-tab -->