
<div class="row">
	<!-- Right Menu -->
    <div class="col-lg-3 col-md-3 col-sm-12">
    </div>
    <div class="clearfix visible-sm"></div>

    <!-- Products -->
    <div class="col-lg-9 col-md-9 col-sm-12">

        <div class="col-lg-12 col-sm-12">
            <span class="title">لیست سفارشات</span>
        </div>
        <!-- Orders Box -->
        <table id="t01" border="10" style="width:100%">
  <tr>
    <th>ID</th>
    <th>تاریخ</th>
  </tr>
  	
    <?php foreach($orders as $order): ?>
        <!-- Order item -->
        <tr>
    <td><a href="<?php echo(sprintf('/admin/customer/edit.php?p=%d',$order['id']));?>"><?php echo ($order['id']); ?></a></td> <!-- قسمت فرستادن آیدی به صفحه مورد نظز -->	
    <td><?php echo ($order['order_date']); ?></td>		
  </tr>
                        
		   
         <!-- End Order 1 -->
    <?php endforeach; ?>
        </table>
    </div>
	
</div>
