<!-- Category Page -->

<div class="row">
	<!-- Right Menu -->
    <div class="col-lg-3 col-md-3 col-sm-12">
        <div class="no-padding">
            <span class="title">
                پرفروش ترین محصولات
            </span>
        </div>
            <?php echo(loadElement('bestselling')); ?>
    </div>
    <div class="clearfix visible-sm"></div>

    <!-- Products -->
    <div class="col-lg-9 col-md-9 col-sm-12">

        <div class="col-lg-12 col-sm-12">
            <span class="title">محصولات این دسته</span>
        </div>
        <!-- Products Box -->
        
        <?php foreach($products as $product): ?>
        <!-- Product item -->
        <div class="col-lg-4 col-sm-4 hero-feature text-center">
            <div class="thumbnail">
                <a href="<?php echo productUrl($product['id']); ?>" >
                    <img src="<?php echo (productImageUrl($product)); ?>" >
                </a>
                <div class="caption prod-caption">
                    <h4>
                        <a href="<?php echo productUrl($product['id']); ?>"><?php echo ($product['product_name']); ?></a>
                    </h4>
                    <p>
                        <?php echo ($product['product_description']); ?>
                    </p>
                        <div class="btn-group btn-group-justified">
                            <a class="btn btn-default"><?php echo ($product['product_price']); ?>&nbsp;ریال</a>
                            <a href="Javascript: (function(){location='<?php echo (addToCartUrl($product)); ?>';})()" class="btn btn-primary">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                            خرید
                            </a>
                        </div>
                    <p></p>
                </div>
            </div>
        </div> <!-- End Product 1 -->
        <?php endforeach; ?>
    </div>
</div>
