<div class="row">
    
        <!-- Slider -->
        <div class="col-lg-9 col-md-12">
            <?php echo(loadElement('sliderNumberOne')); ?>
        </div> <!-- col-lg-9 col-md-12 -->
        <!-- End Slider -->
        
        <!-- Product Selection, visible only on large screen -->
            <?php echo(loadElement('randomProducts')); ?>
        <!-- End Product Selection -->
</div>

<div class="row">
        <div class="col-lg-3 col-md-3 col-sm-12">
            <!-- Categories Menu -->
            <div class="col-lg-12 col-md-12 col-sm-6">
                <div class="no-padding">
                    <span class="title">
                        دسته بندی محصولات
                    </span>
                </div>
                
                <div class="panel-group panel-categories" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading have-sub">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#women" class="collapsed" aria-expanded="false">مد و لباس زنانه</a>
                            </h4>
                        </div>
                        <div id="women" class="panel-collapse collapse" aria-expanded="true">
                            <div class="list-group">
                                <a href="#" class="list-group-item">پیراهن شومیز</a>
                                <a href="#" class="list-group-item">شلوار - شلوارک</a>
                                <a href="#" class="list-group-item">لباس مجلسی</a>
                            </div>
                        </div>
                        <div class="panel-heading have-sub">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#men" class="collapsed" aria-expanded="false">مد و لباس مردانه</a>
                            </h4>
                        </div>
                        <div id="men" class="panel-collapse collapse" aria-expanded="true">
                            <div class="list-group">
                                <a href="#" class="list-group-item">پیراهن</a>
                                <a href="#" class="list-group-item">شلوار</a>
                                <a href="#" class="list-group-item">تیشرت</a>
                            </div>
                        </div>
                        <div class="panel-heading ">
                            <h4 class="panel-title">
                                <a href="#">یک محصول جالب</a>
                            </h4>
                        </div>
   
                    </div>
                </div>
            </div>
            <!-- End Categories Menu -->
            <!-- Best product -->
            <div class="col-lg-12 col-md-12 col-sm-6">
                <div class="no-padding">
                    <span class="title">
                        پرفروش ترین محصولات
                    </span>
                </div>
                
                <?php echo (loadElement('bestselling')); ?>
                
            </div>
            <!-- End Best product -->
        </div>
        
        
        <div class="clearfix visible-sm"></div>
        
        <!-- Products -->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">جدیدترین محصولات</span>
            </div>
            <!-- Products Box -->
            
                <!-- Product -->

                <?php echo (loadElement('latestproduct')); ?>

                <!-- End Product -->

        </div>
        <!-- Products -->
        
        <!-- Products Slider -->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">محصول خوووبــــ ...</span>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12">
                <!-- Slider Number Two -->
                    <?php echo (loadElement('sliderNumberTwo')); ?>
                <!-- End Slider Number Two -->
            </div>
        </div>
        <!-- End Products Slider --> 
    </div>