<div class="row">
    
        <!-- Slider -->
        <div class="col-lg-9 col-md-12">
            <div class="slider">
                <div class="bx-wrapper" style="max-width: 100%; margin: 0 auto;">
                    <div class="bx-viewport" style="max-width: 100%; overflow: hidden; position: relative; max-height: 300px;">
                        <ul class="bxslider">
                            <li>
                                <a href="detail.html"><img src="media/slider-images/banner_slider-1.jpg"></a>
                            </li>
                            <li>
                                <a href="detail.html"><img src="media/slider-images/banner_slider-2.jpg"></a>
                            </li>
                            <li>
                                <a href="detail.html"><img src="media/slider-images/banner_slider-3.jpg"></a>
                            </li>
                        </ul>
                    </div> <!-- bx-viewport -->
                    <div class="bx-controls bx-has-controls-direction">
                        <!-- <div class="bx-controls-direction">
                            <a class="bx-prev">prev</a>
                            <a class="bx-next">next</a>
                        </div> -->
                    </div>
                </div> <!-- bx-wrapper -->
            </div>
        </div> <!-- col-lg-9 col-md-12 -->
        <!-- End Slider -->
        
        <!-- Product Selection, visible only on large screen -->
        <div class="col-lg-3 visible-lg">
            <div class="row text-center">
                <div class="col-lg-12 col-md-12">
                    <div class="thumbnail">
                        <a href="detail.html" style="overflow: hidden; ">
                            <img src="media/product/product-1.jpg" style="width: 253px; height: 219px; max-width: none; max-height: none; ">
                        </a>
                        <div class="caption">
                            <h4>
                                <a href="detail.html">
                                    <?php //echo ($product['desc']); ?>
                                </a>
                            </h4>
                            <p>
                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. 
                            </p>
                            <p></p>
                            
                            <div class="btn-group btn-group-justified">
                                <a href="#" class="btn btn-default">1.000.000 تومان</a>
                                <a href="#" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-shopping-cart"></span>
                                خرید
                                </a>
                            </div>
                            <p></p>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Product Selection -->
    
    
    
    
    
    
    
    
    
</div>