<div class="row">
    
        <!-- Slider -->
        <div class="col-lg-9 col-md-12">
            <div class="slider">
                <div class="bx-wrapper" style="max-width: 100%; margin: 0 auto;">
                    <div class="bx-viewport" style="max-width: 100%; overflow: hidden; position: relative; max-height: 300px;">
                        <ul class="bxslider">
                            <li>
                                <a href="detail.html"><img src="media/slider-images/banner_slider-1.jpg"></a>
                            </li>
                            <li>
                                <a href="detail.html"><img src="media/slider-images/banner_slider-2.jpg"></a>
                            </li>
                            <li>
                                <a href="detail.html"><img src="media/slider-images/banner_slider-3.jpg"></a>
                            </li>
                        </ul>
                    </div> <!-- bx-viewport -->
                    <div class="bx-controls bx-has-controls-direction">
                        <!-- <div class="bx-controls-direction">
                            <a class="bx-prev">prev</a>
                            <a class="bx-next">next</a>
                        </div> -->
                    </div>
                </div> <!-- bx-wrapper -->
            </div>
        </div> <!-- col-lg-9 col-md-12 -->
        <!-- End Slider -->
        
        <!-- Product Selection, visible only on large screen -->
        <div class="col-lg-3 visible-lg">
            <div class="row text-center">
                <div class="col-lg-12 col-md-12">
                    <div class="thumbnail">
                        <a href="detail.html" style="overflow: hidden; ">
                            <img src="media/product/product-1.jpg" style="width: 253px; height: 219px; max-width: none; max-height: none; ">
                        </a>
                        <div class="caption">
                            <h4>
                                <a href="detail.html">
                                    <?php //echo ($product['desc']); ?>
                                </a>
                            </h4>
                            <p>
                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. 
                            </p>
                            <p></p>
                            
                            <div class="btn-group btn-group-justified">
                                <a href="#" class="btn btn-default">1.000.000 تومان</a>
                                <a href="#" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-shopping-cart"></span>
                                خرید
                                </a>
                            </div>
                            <p></p>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Product Selection -->
</div>

<div class="row">
        <div class="col-lg-3 col-md-3 col-sm-12">
            <!-- Categories Menu -->
            <div class="col-lg-12 col-md-12 col-sm-6">
                <div class="no-padding">
                    <span class="title">
                        دسته بندی محصولات
                    </span>
                </div>
                
                <div class="panel-group panel-categories" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading have-sub">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#women" class="collapsed" aria-expanded="false">مد و لباس زنانه</a>
                            </h4>
                        </div>
                        <div id="women" class="panel-collapse collapse" aria-expanded="true">
                            <div class="list-group">
                                <a href="#" class="list-group-item">پیراهن شومیز</a>
                                <a href="#" class="list-group-item">شلوار - شلوارک</a>
                                <a href="#" class="list-group-item">لباس مجلسی</a>
                            </div>
                        </div>
                        <div class="panel-heading have-sub">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#men" class="collapsed" aria-expanded="false">مد و لباس مردانه</a>
                            </h4>
                        </div>
                        <div id="men" class="panel-collapse collapse" aria-expanded="true">
                            <div class="list-group">
                                <a href="#" class="list-group-item">پیراهن</a>
                                <a href="#" class="list-group-item">شلوار</a>
                                <a href="#" class="list-group-item">تیشرت</a>
                            </div>
                        </div>
                        <div class="panel-heading ">
                            <h4 class="panel-title">
                                <a href="#">یک محصول جالب</a>
                            </h4>
                        </div>
   
                    </div>
                </div>
            </div>
            <!-- End Categories Menu -->
            <!-- Best product -->
            <div class="col-lg-12 col-md-12 col-sm-6">
                <div class="no-padding">
                    <span class="title">
                        پرفروش ترین محصولات
                    </span>
                </div>
                <div class="hero-feature">
                    <div class="thumbnail text-center">
                        <a href="detail.html">
                            <img src="media/product/product-8.jpg">
                        </a>
                        <div class="caption prod-caption">
                            <h4>
                                <a href="detail.html">
                                    یک محصول پرفروش
                                </a>
                            </h4>
                            <p>
                                لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. 
                            </p>
                            <div class="btn-group btn-group-justified">
                                <a href="#" class="btn btn-default">1.000.000 تومان</a>
                                <a href="#" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-shopping-cart"></span>
                                خرید
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Best product - Hidden in Small screen -->
                
                <div class="hero-feature hidden-sm">
                    <div class="thumbnail text-center">
                        <a href="detail.html">
                            <img src="media/product/product-8.jpg">
                        </a>
                        <div class="caption prod-caption">
                            <h4>
                                <a href="detail.html">
                                    یک محصول پرفروش
                                </a>
                            </h4>
                            <p>
                                لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. 
                            </p>
                            <div class="btn-group btn-group-justified">
                                <a href="#" class="btn btn-default">1.000.000 تومان</a>
                                <a href="#" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-shopping-cart"></span>
                                خرید
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Best product - Hidden in Small screen -->
                
            </div>
            <!-- End Best product -->
        </div>
        
        
        <div class="clearfix visible-sm"></div>
        
        <!-- Products -->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">جدیدترین محصولات</span>
            </div>
            <!-- Products Box -->
            
                <!-- Product -->

                <?php echo (loadElement('latestproduct')); ?>

                <!-- End Product -->

        </div>
        <!-- Products -->
        
        <!-- Products Slider -->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">محصول خوووبــــ ...</span>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="slider">
                    <div class="bx-wrapper" style="max-width: 100%; margin: 0 auto;">
                        <div class="bx-viewport" style="max-width: 100%;overflow: hidden; position: relative; height: 135px;">
                            <div class="bx-wrapper" style="max-width: 920px;"><div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 126px;"><ul class="bxslider2" style="width: 3215%; position: absolute; -webkit-transition-duration: 0s; transition-duration: 0s; -webkit-transform: translate3d(-1240px, 0px, 0px);"><li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;" class="bx-clone">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-1.jpg" title="یک توضیح !"></a>
                                <div class="bx-caption"><span>یک توضیح !</span></div></li><li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;" class="bx-clone">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-2.jpg"></a>
                                </li><li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;" class="bx-clone">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-3.jpg"></a>
                                </li>
                                <li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-1.jpg" title="یک توضیح !"></a>
                                <div class="bx-caption"><span>یک توضیح !</span></div></li>
                                <li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-2.jpg"></a>
                                </li>
                                <li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-3.jpg"></a>
                                </li>
                            <li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;" class="bx-clone">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-1.jpg" title="یک توضیح !"></a>
                                <div class="bx-caption"><span>یک توضیح !</span></div></li><li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;" class="bx-clone">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-2.jpg"></a>
                                </li><li style="float: left; list-style: none; position: relative; width: 300px; margin-right: 10px;" class="bx-clone">
                                    <a href="detail.html"><img src="media/slider-images/banner_slider-3.jpg"></a>
                                </li></ul></div><div class="bx-controls bx-has-controls-direction"><div class="bx-controls-direction"><a class="bx-prev" href="">Prev</a><a class="bx-next" href="">Next</a></div></div></div>
                        </div> <!-- bx-viewport -->
                        <div class="bx-controls bx-has-controls-direction">
                            <!-- <div class="bx-controls-direction">
                                <a class="bx-prev">prev</a>
                                <a class="bx-next">next</a>
                            </div> -->
                        </div>
                    </div> <!-- bx-wrapper -->
                </div>
            </div>
        </div>
        <!-- End Products Slider --> 
    </div>